version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install
  post_build:
    commands:
      - cp -R src/views dist/views
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
