services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

# TODO: Add Redis service
  
volumes:
  mongodb_data: